  
version: 2.1
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: circleci/node # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      #- checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Build front-end
          command: |
            npm install
            npm run build
      - store_artifacts: # buildで出力されたファイルをArtifactsに保存する
          path: test-result.xml
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-result.xml
  test:
    docker:
      - image: circleci/node:12-browsers 
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Test front-end
          command: |
            npm install
            npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  cache:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - cache:
          requires:
            - build