version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14 # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Build front-end
          command: |
            npm install
            npm build
  test:
    docker:
      - image: circleci/node:14 # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Test front-end
          command: |
            npm install
            npm test
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
          - build
      ### Add the job