  
version: 2.1
orbs:
  slack: circleci/slack@4.4.2
jobs:
  build:
    # working_directory: /tmp
    docker:
      - image: circleci/node # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Build front-end
          command: |
            npm install && npm run build
      - slack/notify:
          event: pass
          template: basic_fail_1
      - save_cache:
          paths:
            - node_modules
          key: v1-deps

      - store_artifacts: # buildで出力されたファイルをArtifactsに保存する
          path: dist
      # - store_artifacts:
      #     path: coverage
      # - store_test_results:
      #     path: test-result.xml
  test:
    docker:
      - image: circleci/node:12-browsers 
    
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - restore_cache:
          key: v1-deps
      - run : 
          name: Test front-end
          command: |
            npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build